apiVersion: apps/v1
kind: Deployment
metadata:
  name: okmi4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okmi4
  template:
    metadata:
      labels:
        app: okmi4
    spec:
      containers:
      - image: okteto.dev/okmi4:latest
        name: okmi4
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: ParameterSSENCYPT
          value: "chacha20-ietf-poly1305"
        - name: AUUID
          value: "c1d40f0f-eb10-4b30-bc66-f172b223fe45"
